"""
Model info API: expose trained model metadata.

GET /model/info returns model_metadata.json contents validated against a
strict Pydantic schema. Read-only; does not modify any artifacts.
"""

import logging

from fastapi import APIRouter, HTTPException

from backend.app.schemas.model_metadata import ModelMetadataResponse
from backend.app.services.model_loader import get_model_metadata

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/model", tags=["model"])


@router.get("/info", response_model=ModelMetadataResponse)
async def model_info() -> ModelMetadataResponse:
    """
    Return model metadata (version, features, training date range, hyperparameters,
    validation metrics, residual std).

    Loads from artifacts/models/model_metadata.json. Returns 500 if the file
    has not been generated by training yet, or if the schema does not match.
    """
    try:
        raw = get_model_metadata()
    except RuntimeError as exc:
        logger.error("Model metadata unavailable: %s", exc)
        raise HTTPException(status_code=500, detail=str(exc)) from exc

    try:
        metadata = ModelMetadataResponse(**raw)
    except Exception as exc:
        logger.error("Model metadata schema validation failed: %s", exc)
        raise HTTPException(
            status_code=500,
            detail=f"Model metadata schema invalid: {exc}",
        ) from exc

    logger.info(
        "Served model info: version=%s, features=%d, sample_size=%d",
        metadata.model_version,
        metadata.feature_count,
        metadata.sample_size,
    )
    return metadata
