"""
Model info API: expose trained model metadata.

GET /model/info returns model_metadata.json contents.
Read-only; does not modify any artifacts.
"""

import logging

from fastapi import APIRouter, HTTPException

from backend.app.services.model_loader import get_model_metadata

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/model", tags=["model"])


@router.get("/info")
async def model_info() -> dict:
    """
    Return model metadata (version, features, training date range, residual stats).

    Loads from artifacts/models/model_metadata.json. Returns 500 if the file
    has not been generated by training yet.
    """
    try:
        metadata = get_model_metadata()
    except RuntimeError as exc:
        logger.error("Model metadata unavailable: %s", exc)
        raise HTTPException(status_code=500, detail=str(exc)) from exc

    logger.info(
        "Served model info: version=%s, feature_count=%d",
        metadata.get("model_version", "unknown"),
        metadata.get("feature_count", 0),
    )
    return metadata
